### ISSUE TITLE
user-can-see-their-car

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/driving-game#1]
![image](https://user-images.githubusercontent.com/84432043/133665630-7220b7ce-d3df-48fb-8c65-afd403dba4de.png)

## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Set background to green color 
- [x] Place car on the top left of the body element
- [x] Resize accordingly 
- [x] Ensure car is facing right direction 
- [x] Remove unnecessary CSS
- [x] Fix any errors
- [x] Test any functionality 
- [x] Continue onto next Issue
