### ISSUE TITLE
user-can-turn-their-car

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/driving-game#3]
https://user-images.githubusercontent.com/84432043/133673269-415fca21-0737-4c0b-ba88-b930b568ce27.mov

 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] On keydown up move up
- [x] On keydown down move down
- [x] On keydown left move left
- [x] On keydown right move right
